# Generated by Django 6.0.3 on 2026-03-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cash", models.IntegerField()),
                ("financial", models.FloatField()),
                ("human", models.FloatField()),
                ("green", models.FloatField()),
                ("resilience", models.FloatField()),
                ("digital", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("choice", models.CharField(max_length=1)),
                ("R", models.FloatField()),
                ("E", models.FloatField()),
                ("S", models.FloatField()),
                ("B", models.FloatField()),
                ("T", models.FloatField()),
                ("P", models.FloatField()),
                ("A", models.FloatField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gamesession",
                    ),
                ),
            ],
        ),
    ]
